Базовая стилизация
htmlacademy-htmlcss/2512279-sedona-1 pull request #3
Opened 2024-05-08 15:15 UTC by YoungBaffet

2024-05-15 14:46 UTC, Kartaviy-arteom requested changes

2024-05-15 14:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +  font-display: swap;
у нас не используется это начертание

2024-05-15 14:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +.white{color: #ffffff;}
написание стилей в единым подходом к форматированию

2024-05-15 14:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +.newsletter-button {
у кнопки рендерится системный шрифт

2024-05-20 16:13 UTC, YoungBaffet commented
Не разобрался как разметить каталог

2024-05-22 16:05 UTC, merged